# Generated by Django 3.2.7 on 2022-04-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='sc_total_price',
            field=models.FloatField(default=0),
        ),
    ]
