# Generated by Django 3.2.7 on 2022-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0002_alter_shoppingcart_sc_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
