# Generated by Django 3.2.7 on 2022-04-18 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0006_remove_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
