# Generated by Django 3.2.7 on 2022-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='/home/jlocamuz/perro.png', upload_to=''),
        ),
    ]
