# Generated by Django 3.2.7 on 2022-04-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
