# Generated by Django 4.0.3 on 2022-04-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro1', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='distributor_id',
            new_name='distributor',
        ),
    ]
